version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - '9200:9200'
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - my_network
  app:
    build: .
    container_name: node_app
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - CLIENT_ID=<CLIENT_ID>           
      - CLIENT_SECRET= <CLIENT_SECRET>
      - TENANT_ID=<TENANT_ID>
      - REDIRECT_URI=http://localhost:3000/auth/outlook/callback
      - ELASTIC_SEARCH_URI=http://elasticsearch:9200
    volumes:
      - .:/usr/src/app
    depends_on:
      - elasticsearch
    networks:
      - my_network  # Added this line

 

networks:
  my_network:
    driver: bridge

volumes:
  esdata:
    driver: local
